---
- name: Install fail2ban
  become: true
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Configure fail2ban
  become: true
  ansible.builtin.template:
    src: fail2ban.conf.j2
    dest: /etc/fail2ban/fail2ban.conf
    mode: 0600
    owner: root
  notify:
    - Reload fail2ban

- name: Configure SSH ban settings
  become: true
  ansible.builtin.template:
    src: sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    mode: 0644
    owner: root
  notify:
    - Reload fail2ban

- name: Enable fail2ban
  become: true
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
