---
- name: Clear old known host entries
  become: true
  ansible.builtin.file:
    path: /etc/ssh/ssh_known_hosts
    state: absent
  when: reset is defined and reset

- name: Synchronize known host entries
  become: true
  ansible.builtin.known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: "{{ item.name }}"
    key: "{{ item.key }}"
    state: present
  loop: "{{ security_known_hosts | mandatory }}"
