- name: Restart ssh
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload fail2ban
  become: true
  ansible.builtin.service:
    name: fail2ban
    state: reloaded
