---
- name: Install snap
  become: true
  ansible.builtin.apt:
    name: snapd
    state: present

- name: Install certbot
  become: true
  community.general.snap:
    name:
      - core
      - certbot
    classic: true
    state: present

- name: Link binary
  become: true
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
