---
- name: Install certbot
  ansible.builtin.include_tasks:
    file: install.yml

- name: Configure certbot acme account
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Create certificates
  ansible.builtin.include_tasks:
    file: standard.yml
  when: certbot_dns_plugin is not defined

- name: Create certificates
  ansible.builtin.include_tasks:
    file: wildcard.yml
  when: certbot_dns_plugin is defined

- name: Setup renewals
  ansible.builtin.include_tasks:
    file: renewal.yml

- name: Configure firewall
  ansible.builtin.include_role:
    name: firewall
    tasks_from: install_rules.yml
  vars:
    firewall_rules:
      - chain: INPUT
        protocol: TCP
        source: "{{ certbot_whitelisted_sources | default(omit, true) }}"
        destination_ports:
          - 80
          - 443
        comment: Certificate renewal connections
      - chain: OUTPUT
        