- name: Update repository
  become: true
  ansible.builtin.apt:
    autoclean: true
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: true
    autoremove: true

- name: Verify if reboot is required
  become: true
  register: reboot_required
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: false

- name: Reboot system
  become: true
  ansible.builtin.reboot:
    msg: "System reboot initiated by Ansible for updates"
  when: reboot_required.stat.exists and maintenance_permit_reboot
